# Generated by Django 4.1.7 on 2023-02-27 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=20)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("txn_type", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=50)),
                ("subcategory", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ledger"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Todo",),
    ]
