# Generated by Django 4.1.7 on 2023-03-09 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_ledger_transaction_delete_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name="ledger", old_name="account", new_name="name",
        ),
        migrations.RemoveField(model_name="ledger", name="balance",),
        migrations.RemoveField(model_name="ledger", name="date",),
        migrations.AddField(
            model_name="ledger",
            name="general_ledger",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.generalledger",
            ),
        ),
    ]
