# Generated by Django 4.1.7 on 2023-03-09 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_generalledger_rename_account_ledger_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="general_ledger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.generalledger"
            ),
        ),
    ]
