# Generated by Django 4.1.7 on 2023-03-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_ledger_general_ledger"),
    ]

    operations = [
        migrations.RemoveField(model_name="ledger", name="name",),
        migrations.AlterField(
            model_name="ledger",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
