# Generated by Django 4.1.7 on 2023-03-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_ledger_name_alter_ledger_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
